### PR TITLE
fix badges in pr #24

### PR DESCRIPTION
**Pull request by Chezka109**
update badges in pr #24

### CODE REVIEW

**Comment by PCain02** [comment]
Hello @Chezka109 thanks for working on this! Quick question,  why isn't the build passing currently? Also is this supposed to be the PR we merge instead of the other two?

**Comment by PCain02** [comment]
Also what about your amazing logo?

**Comment by Chezka109** [comment]
@PCain02, so the build is failing because of a syntax error in the yml file. I couldn't find exactly what was wrong but I believe there are duplicates in the `build.yml` file. I am meeting with @gkapfham to talk more about this problem!

**Comment by gkapfham** [comment]
Hello @Chezka109 this build is failing. Can you please repair it and then let us know when it is ready for review? Until then I am going to mark this as a draft PR, okay?

**Comment by gkapfham** [comment]
Also @Chezka109 you have a commit with only the message of `fix` which does not adhere to our team's standard for commit messages.

**Comment by Chezka109** [comment]
@gkapfham I made a new branch for the badges and the build is passing there. I am closing this PR.

**Pull request closed without merging**
