### PR TITLE
feat: README Badges and Execexam Logo

### LINKED ISSUE #16: Feature: Add badges to ReadMe
Description: The current version of execexam does not have any badges indicating a passing build. Additionally, it does not have any badges that indicate the PyPI version. 

Proposed Solution: Implement badges that display useful information to the viewer at a glance. Research the different types of badges available and pick the best ones for the project. Update the build.yml file to create and update these badges.

### PR DESCRIPTION
**Pull request by Chezka109**
**Pull Request: Add Dynamic Badges and Create Logo for `execexam`**

**Contributors:**
- Chezka Quinola (@Chezka109)

**Linked Issue:**
- Resolves #16 

**Labels:**
- `enhancement`
- `infrastructure`

**Description:**
This pull request introduces two key updates to the `execexam` project:

1. **Dynamic Badges:**
   - Added a dynamic code coverage badge that updates its color based on the current test coverage percentage. This allows users to instantly see the coverage status at a glance.
   - Implemented a maintenance status badge to reflect the ongoing support and development of the project.
   - Future additions will include badges for the PyPI version and a passing build status, providing further transparency into the project state.

2. **Project Logo:**
   - Created and added a new logo for `execexam` to improve project branding and visibility. The logo will be displayed prominently in the repository’s README file.

**Coverage:**
- Test coverage has been maintained with these changes. The coverage badge confirms that the tests are running and coverage is accurately reported.

**Testing:**
- This PR has been tested on:
  - **Ubuntu 22.04 LTS** via GitHub Actions
  - **macOS Monterey**
  - **Windows 11**
- Tests were conducted using the project's continuous integration (CI) pipeline to ensure that badges are dynamically updated and the logo is properly displayed.

**Screenshots:**

- **Dynamic Coverage Badge:**

   Coverage Badge

- **New Project Logo:**

   execexam Logo

### CODE REVIEW

**Comment by gkapfham** [comment]
Hello @Chezka109 what is the ordering for the merging of this PR and some of our other PRs?

**Review by boulais01 — COMMENTED** [review]
A few thoughts I'd like to bring up before I approve this.

1. I am also curious about if this needs to be merged before/after any other PRs

2. Why did you remove the comments in build.yml file?

3. This reduction of the test suite does not follow general testing conventions. Would you mind offering some justification for this alteration? This is especially a concern as based on your doc string, you're calling it utility functions instead of test functions.

**Comment by Chezka109** [comment]
@boulais01, the comments being removed were not on purpose. the reason why the build.yml was failing before was because there were duplicates in the .yml file. once i found that out, i had a program fix the yml file and remove the duplicates. for the test_util.py, that was an old test suite that has not been removed. i will remove them right now and add the comments back to the yml file.

**Comment by Chezka109** [comment]
@gkapfham, i feel like it's better to merge this PR first before @dyga01 and @hannahb09's test cases. I think it makes more sense and requires less work and has a lower chance of not working for this to be merged. @dyga01 and @hannahb09 what do you think?

**Comment by gkapfham** [comment]
@dyga01 and @hannahb09 can you please respond to the prior question? Thanks!

**Comment by dyga01** [comment]
@Chezka109 and @gkapfham That sounds good to me. Hannah and I just have to work on fixing merge conflicts in our PR.

**Review by boulais01 — APPROVED** [review]

**Comment by gkapfham** [comment]
@Chezka109 and @dyga01 and @hannahb09 and others, what is the status update on the ordering?

**Comment by Chezka109** [comment]
@gkapfham i thought it was agreed that my PR was being merged first

**Comment by gkapfham** [comment]
@Chezka109 are you aware that another PR has _merged_ your PR into theirs? Please check one of the PRs related to the coverage tracking and improvements. @dyga01 can you comment further?

**Review by AlishChhetri — APPROVED** [review]
Looks good to me! I don’t have a strong preference on whether PR 38 or PR 40 is merged first. However, please note that PR 38 will have a significant impact on the validity of the test cases due to changes in how the test suite is run. This may cause the build to fail if it relies on maintaining a specific coverage rate, or the badge may simply reflect a lower coverage percentage.

**Comment by CalebKendra** [comment]
This PR now has two TL reviews, we now need a student review correct?

**Pull request merged**
