### PR TITLE
Exexcexam motivator

### PR DESCRIPTION
**Pull request by PhilipOlwoc**
A motivator for execexam

### CODE REVIEW

**Comment by gkapfham** [comment]
Hello @PhilipOlwoc can you please explain what this is and how it works?

**Comment by gkapfham** [comment]
Hello @PhilipOlwoc can you please respond to my prior question?

**Comment by gkapfham** [comment]
Hello @PhilipOlwoc please note that this branch has conflicts. Can you please resolve them?

**Comment by gkapfham** [comment]
Hello @PhilipOlwoc this PR has commits that are largely (if not entirely) from another PR. Can you please commit any working version of this system that you have so that it is available in draft form? Also, can you please explain this feature in greater detail and give examples of how it is supposed to work? Thanks!

**Comment by gkapfham** [comment]
Hello @PhilipOlwoc this PR has a failing build. Can you please look into this further?

**Comment by gkapfham** [comment]
Hello @PhilipOlwoc can you please furnish screen shots that show how this is working?

**Comment by gkapfham** [comment]
Hello @PhilipOlwoc this PR has conflicts that must be resolved. Can you resolve them?

**Comment by gkapfham** [comment]
Hello @PhilipOlwoc this PR has conflicts that must be resolved. Can you resolve them?

**Comment by AlishChhetri** [comment]
What is the progress on this PR? Please provide a detailed report, and make sure to include screenshots of the output(s).

**Pull request closed without merging**
