### PR TITLE
Fix/correct pytest plugin

### PR DESCRIPTION
**Pull request by gkapfham**
This pull request fixes a defect inside of `execexam` that prevented it from working correctly because it _both_ declared that it _was_ a Pytest plugin and that it _contained_ a Pytest plugin. This causes `pytest` to not work correctly and then there was no output when running an `execexam` command.

Additional improvements:

- There is some dependency that is not correctly using Pydantic and this causes warnings to appear. As such, we added code that will disable those warnings from being displayed in the console.

### CODE REVIEW

**Comment by PCain02** [comment]
I tested the code from this PR on Windows and it worked properly. I recommend pushing this PR as long as it works for the other operating systems.

**Comment by hemanialaparthi** [comment]
I tested this PR on mac and it worked. I approve that this works and it can be merged!

**Comment by rebekahrudd** [comment]
I tested this new code on Linux. These changes work and don't break the code!

**Comment by TitusSmith33** [comment]
I am also on a Windows OS, and I was able to get it to work correctly using this PR, I recommend pushing!!

**Comment by hannahb09** [comment]
I tested it and it works

**Pull request merged**
