### PR TITLE
fix: Update Issue Templates to be Selectable on GitHub

### PR DESCRIPTION
**Pull request by PCain02**
Issue templates are currently not selectable. Now it should be a popup when you go to make a new issue you can select from the choices. 

2. List the names of those who contributed to the project.
@PCain02

3. Link the issue the pull request is meant to fix/resolve.
https://github.com/GatorEducator/execexam/issues/44

4. Describe the contents and goal of the pull request.
This PR adds the ability to select an issue template when going to make an issue. The choices are bug, feature, or custom.

5. What operating systems has this been tested on? How were these tests conducted?

This is a feature on GitHub so it does not really apply but I am on Windows 10

7. Add all labels that apply. (e.g., documentation, ready-for-review)
Infrastructure

8. Will coverge be maintained/increased?
This does not affect coverage.

9. Include a code block and/or screenshots displaying the functionality of your
feature, if applicable/possible.

### CODE REVIEW

**Review by rebekahrudd — APPROVED** [review]
Looks good to me! Is there something we should test locally for this update?

**Review by hannahb09 — APPROVED** [review]
looked at the changes looks good to me

**Comment by PCain02** [comment]
Yeah you can't really test anything since this was a setting change on GitHub and it won't be active until there is approval. The only changes were the Markdown documents so it's a pretty safe PR.

**Review by AlishChhetri — APPROVED** [review]
LGTM!

**Review by boulais01 — APPROVED** [review]
LGTM. Only note is that the custom template is uncustomized, if that's intentional you're clear.

**Comment by PCain02** [comment]
@gkapfham Can this get merged since I got all the approvals?

**Comment by PCain02** [comment]
> LGTM. Only note is that the custom template is uncustomized, if that's intentional you're clear.

Yep! I just wanted to leave that for people to make their own.

**Pull request merged**
